<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body{font-family:Arial,sans-serif;background:#f3f4f6;margin:0;padding:20px}
  .wrap{max-width:640px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.08)}
  .header{background:#dc2626;padding:28px 32px;color:#fff}
  .header h1{margin:0;font-size:20px} .header p{margin:6px 0 0;font-size:13px;opacity:.85}
  .body{padding:28px 32px}
  .alert-box{background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:16px;margin-bottom:20px}
  table{width:100%;border-collapse:collapse;margin-top:12px;font-size:13px}
  th{background:#f9fafb;padding:10px 12px;text-align:left;color:#6b7280;font-size:11px;text-transform:uppercase;border-bottom:2px solid #e5e7eb}
  td{padding:10px 12px;border-bottom:1px solid #f3f4f6}
  .badge-danger{display:inline-block;background:#fee2e2;color:#991b1b;padding:2px 8px;border-radius:999px;font-size:11px;font-weight:600}
  .badge-ok{display:inline-block;background:#d1fae5;color:#065f46;padding:2px 8px;border-radius:999px;font-size:11px;font-weight:600}
  .footer{background:#f9fafb;padding:16px 32px;text-align:center;font-size:11px;color:#9ca3af;border-top:1px solid #e5e7eb}
</style>
</head>
<body>
<div class="wrap">
  <div class="header">
    <h1>⚠️ Low Stock Alert</h1>
    <p>{{ $items->count() }} item(s) require immediate restocking</p>
  </div>
  <div class="body">
    <div class="alert-box">
      <strong style="color:#dc2626">Action Required:</strong> The following items have fallen below their minimum alert quantity.
      Please restock them as soon as possible to avoid stockouts.
    </div>
    <table>
      <thead>
        <tr>
          <th>Item</th>
          <th>SKU</th>
          <th>Warehouse</th>
          <th>Current Qty</th>
          <th>Alert Qty</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        @foreach($items as $s)
        <tr>
          <td><strong>{{ $s->item->name }}</strong><br><span style="color:#6b7280;font-size:11px">{{ $s->item->category->name }}</span></td>
          <td style="font-family:monospace;color:#2563eb">{{ $s->item->sku }}</td>
          <td>{{ $s->warehouse->name }}</td>
          <td style="color:#dc2626;font-weight:600">{{ number_format($s->quantity, 2) }} {{ $s->item->unit->symbol }}</td>
          <td>{{ number_format($s->item->alert_quantity, 2) }}</td>
          <td>@if($s->quantity <= 0)<span class="badge-danger">OUT OF STOCK</span>@else<span class="badge-danger">LOW STOCK</span>@endif</td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
  <div class="footer">
    Generated by WMS Pro &bull; {{ now()->format('d M Y H:i') }}
  </div>
</div>
</body>
</html>
