<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <style>
    body {
      font-family: Arial, sans-serif;
      background: #f3f4f6;
      margin: 0;
      padding: 20px
    }

    .wrap {
      max-width: 640px;
      margin: 0 auto;
      background: #fff;
      border-radius: 12px;
      overflow: hidden;
      box-shadow: 0 2px 8px rgba(0, 0, 0, .08)
    }

    .header {
      background: #d97706;
      padding: 28px 32px;
      color: #fff
    }

    .header h1 {
      margin: 0;
      font-size: 20px
    }

    .header p {
      margin: 6px 0 0;
      font-size: 13px;
      opacity: .85
    }

    .body {
      padding: 28px 32px
    }

    .info-box {
      background: #fffbeb;
      border: 1px solid #fde68a;
      border-radius: 8px;
      padding: 16px;
      margin-bottom: 20px
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 12px;
      font-size: 13px
    }

    th {
      background: #f9fafb;
      padding: 10px 12px;
      text-align: left;
      color: #6b7280;
      font-size: 11px;
      text-transform: uppercase;
      border-bottom: 2px solid #e5e7eb
    }

    td {
      padding: 10px 12px;
      border-bottom: 1px solid #f3f4f6
    }

    .badge-danger {
      display: inline-block;
      background: #fee2e2;
      color: #991b1b;
      padding: 2px 8px;
      border-radius: 999px;
      font-size: 11px;
      font-weight: 600
    }

    .badge-warning {
      display: inline-block;
      background: #fef3c7;
      color: #92400e;
      padding: 2px 8px;
      border-radius: 999px;
      font-size: 11px;
      font-weight: 600
    }

    .total-row {
      background: #f9fafb;
      font-weight: 700
    }

    .footer {
      background: #f9fafb;
      padding: 16px 32px;
      text-align: center;
      font-size: 11px;
      color: #9ca3af;
      border-top: 1px solid #e5e7eb
    }
  </style>
</head>

<body>
  <div class="wrap">
    <div class="header">
      <h1>💰 Outstanding Payment Due</h1>
      <p>{{ $records->count() }} {{ $type === 'sales' ? 'Sales Invoices' : 'Purchase Orders' }} with pending payments</p>
    </div>
    <div class="body">
      <div class="info-box">
        <strong style="color:#d97706">Total Due: PKR {{ number_format($records->sum('due_amount'), 2) }}</strong><br>
        Please follow up on the following outstanding {{ $type === 'sales' ? 'customer' : 'supplier' }} payments.
      </div>
      <table>
        <thead>
          <tr>
            <th>Reference</th>
            <th>{{ $type === 'sales' ? 'Customer' : 'Supplier' }}</th>
            <th>Date</th>
            <th>Total</th>
            <th>Paid</th>
            <th>Due</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          @foreach($records as $r)
          <tr>
            <td style="font-family:monospace;color:#2563eb">{{ $r->reference }}</td>
            <td><strong>{{ $type === 'sales' ? $r->customer->name : $r->supplier->name }}</strong></td>
            <td>{{ ($type === 'sales' ? $r->sale_date : $r->purchase_date)->format('d M Y') }}</td>
            <td>PKR {{ number_format($r->total_amount, 2) }}</td>
            <td style="color:#059669">PKR {{ number_format($r->paid_amount, 2) }}</td>
            <td style="color:#dc2626;font-weight:600">PKR {{ number_format($r->due_amount, 2) }}</td>
            <td>@if($r->payment_status === 'unpaid')<span class="badge-danger">Unpaid</span>@else<span class="badge-warning">Partial</span>@endif</td>
          </tr>
          @endforeach
          <tr class="total-row">
            <td colspan="5" style="text-align:right;padding-right:12px">Total Due:</td>
            <td style="color:#dc2626">PKR {{ number_format($records->sum('due_amount'), 2) }}</td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="footer">
      Generated by WMS Pro &bull; {{ now()->format('d M Y H:i') }}
    </div>
  </div>
</body>

</html>